### ISSUE TITLE
Combat specialist gets +2 attacks

### ISSUE THREAD

**Issue by kHaosAntePortas** [Floppy/scriptorum#180]
My plague marine fighter with combat speciality gets 2+2 attacks in fight phase.

**Comment by Floppy** [comment]
Thanks! It's showing as 2+2 in the badge, I assume? Are there any other weapons involved? If there's a weapon that might give an additional attack (chainsword perhaps?), it's probably being included as well. I should perhaps find a way of showing that more clearly rather than rolling them together as one. If you can attach the roster, I can check for certain...

**Comment by Floppy** [comment]
pasting from reddit comment:

> i have a plague marine with great cleaver as combat specialist and your app tells me it gets 2+2 attacks in fight phase. Might be i havnt drank enough coffe yet but it shoul only be 2+1 attacks i believe. Greetings

**Comment by Floppy** [comment]
The plague cleaver doesn't grant an additional attack, so yes, there's something wrong here I think. It *might* be coming from the `Death to the False Emperor` rule, but that's probably being a bit overzealous with the additions.

**Comment by Floppy** [comment]
Feels to me that rules like `Each time the bearer fights, it can make 1 additional attack with this weapon` should be included automatically, as there's no situation in which you wouldn't do it, but the more chancy ones like additional attacks if you roll a 6 should probably be left out of the total.
