### ISSUE TITLE
Icon for comms specialist not working in particular roster (attached)

### ISSUE THREAD

**Issue by r4dian** [Floppy/scriptorum#183]
It's using her gear instead of specialism ?

`/icons/vox%20caster%20+%20hot-shot%20laspistol.svg`

[Stage of Pain 3.zip](https://github.com/Floppy/scriptorum/files/5332459/Stage.of.Pain.3b.zip)

**Comment by Floppy** [comment]
Oh, that's a fun one. I'll find out what's up, thanks for attaching the roster 👍

**Comment by Floppy** [comment]
OK, this is because the xpath used to parse the specialism isn't quite good enough. It looks for `selection`s with certain things inside them that I thought were only used in specialism selections, but apparently this weapon choice does the same thing - could be a combi-weapon thing perhaps. So, I need to improve the xpath.

**Comment by Floppy** [comment]
Should be fixed now!
